### GET ALL CLASSROOM IDS
# @name http://localhost:8080/api/v1/classrooms
GET http://localhost:8080/api/v1/classrooms
Authorization: Basic user1 pass1

### GET ALL ACTIVITIES FROM GIVEN CLASS
# @name http://localhost:8080/api/v1/activities
GET http://localhost:8080/api/v1/activities
Authorization: Basic user1 pass1
Content-Type: application/json

{
  "classRoomQrCode": "CYFX"
}

### ASSIGN USER TO ACTIVITY
# @name http://localhost:8080/api/v1/activities
POST http://localhost:8080/api/v1/activities
Authorization: Basic user1 pass1
Content-Type: application/json

{
  "registrationQrCode": "{\"activityId\":\"f846ec1d-39a0-4ea7-b59a-3b0dee3b97ed\",\"sessionId\":\"A8426312432A7F30D2449A02BFDA3E6A\",\"expiresAt\":\"2023-10-15T14:11:19.268714186\"}"
}

